FROM node:22-alpine
WORKDIR /app
COPY frontend/nuxt-app/package.json frontend/nuxt-app/package-lock.json ./
RUN npm ci
COPY frontend/nuxt-app .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
